import {ConfigFile} from '../../generator/types';
export const config: ConfigFile = {
  rootOptions: {
    pools: ['AaveV3EthereumEtherFi'],
    title: 'EtherFi Ethereum Activation',
    shortName: 'EtherFiEthereumActivation',
    date: '20240902',
    author: 'Catapulta',
    discussion:
      'https://governance.aave.com/t/arfc-deploy-an-etherfi-stablecoin-aave-v3-instance/18440',
    snapshot:
      'https://snapshot.org/#/aave.eth/proposal/0x4acd11c6100a6b85a553e21359f3720fa5cd4783a76c77857436ace134f88c05',
    votingNetwork: 'POLYGON',
  },
  poolOptions: {
    AaveV3EthereumEtherFi: {
      configs: {
        FLASH_BORROWER: {address: '0x0274a704a6D9129F90A62dDC6f6024b33EcDad36'},
        ASSET_LISTING: [
          {
            assetSymbol: 'weETH',
            decimals: 18,
            priceFeed: '0xf112aF6F0A332B815fbEf3Ff932c057E570b62d3',
            ltv: '78',
            liqThreshold: '81',
            liqBonus: '6',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'DISABLED',
            flashloanable: 'ENABLED',
            stableRateModeEnabled: 'DISABLED',
            borrowableInIsolation: 'DISABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '0',
            supplyCap: '50000',
            borrowCap: '0',
            rateStrategyParams: {
              optimalUtilizationRate: '0',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '0',
              variableRateSlope2: '0',
            },
            eModeCategory: 'AaveV3EthereumEtherFiEModes.NONE',
            asset: '0xCd5fE23C85820F7B72D0926FC9b05b43E359b7ee',
          },
          {
            assetSymbol: 'USDC',
            decimals: 6,
            priceFeed: '0x736bF902680e68989886e9807CD7Db4B3E015d3C',
            ltv: '0',
            liqThreshold: '0',
            liqBonus: '0',
            debtCeiling: '0',
            liqProtocolFee: '0',
            enabledToBorrow: 'ENABLED',
            flashloanable: 'ENABLED',
            stableRateModeEnabled: 'DISABLED',
            borrowableInIsolation: 'DISABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '10',
            supplyCap: '140000000',
            borrowCap: '135000000',
            rateStrategyParams: {
              optimalUtilizationRate: '90',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '6.5',
              variableRateSlope2: '60',
            },
            eModeCategory: 'AaveV3EthereumEtherFiEModes.NONE',
            asset: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
          },
          {
            assetSymbol: 'PYUSD',
            decimals: 6,
            priceFeed: '0x150bAe7Ce224555D39AfdBc6Cb4B8204E594E022',
            ltv: '0',
            liqThreshold: '0',
            liqBonus: '0',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'ENABLED',
            flashloanable: 'ENABLED',
            stableRateModeEnabled: 'DISABLED',
            borrowableInIsolation: 'DISABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '20',
            supplyCap: '60000000',
            borrowCap: '15000000',
            rateStrategyParams: {
              optimalUtilizationRate: '90',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '5.5',
              variableRateSlope2: '80',
            },
            eModeCategory: 'AaveV3EthereumEtherFiEModes.NONE',
            asset: '0x6c3ea9036406852006290770BEdFcAbA0e23A0e8',
          },
          {
            assetSymbol: 'FRAX',
            decimals: 18,
            priceFeed: '0x45D270263BBee500CF8adcf2AbC0aC227097b036',
            ltv: '0',
            liqThreshold: '0',
            liqBonus: '0',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'ENABLED',
            flashloanable: 'ENABLED',
            stableRateModeEnabled: 'DISABLED',
            borrowableInIsolation: 'DISABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '20',
            supplyCap: '54000000',
            borrowCap: '12000000',
            rateStrategyParams: {
              optimalUtilizationRate: '90',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '5.5',
              variableRateSlope2: '80',
            },
            eModeCategory: 'AaveV3EthereumEtherFiEModes.NONE',
            asset: '0x853d955aCEf822Db058eb8505911ED77F175b99e',
          },
        ],
      },
      cache: {blockNumber: 20662348},
    },
  },
};
