import {ConfigFile} from '../../generator/types';
export const config: ConfigFile = {
  rootOptions: {
    author: 'BGD Labs @bgdlabs',
    pools: [
      'AaveV3Ethereum',
      'AaveV3EthereumLido',
      'AaveV3Polygon',
      'AaveV3Avalanche',
      'AaveV3Optimism',
      'AaveV3Arbitrum',
      'AaveV3Metis',
      'AaveV3Base',
      'AaveV3Gnosis',
      'AaveV3Scroll',
      'AaveV3BNB',
      'AaveV3ZkSync',
      'AaveV3Linea',
    ],
    title: 'Clinic steward activation',
    shortName: 'ClinicStewardActivation',
    date: '20250228',
    discussion: 'https://governance.aave.com/t/arfc-bgd-aave-clinicsteward/21209',
    snapshot: 'will add later',
    votingNetwork: 'POLYGON',
  },
  poolOptions: {
    AaveV3Ethereum: {configs: {OTHERS: {}}, cache: {blockNumber: 21943835}},
    AaveV3EthereumLido: {configs: {OTHERS: {}}, cache: {blockNumber: 21943836}},
    AaveV3Polygon: {configs: {OTHERS: {}}, cache: {blockNumber: 68470179}},
    AaveV3Avalanche: {configs: {OTHERS: {}}, cache: {blockNumber: 57999333}},
    AaveV3Optimism: {configs: {OTHERS: {}}, cache: {blockNumber: 132567395}},
    AaveV3Arbitrum: {configs: {OTHERS: {}}, cache: {blockNumber: 310733493}},
    AaveV3Metis: {configs: {OTHERS: {}}, cache: {blockNumber: 19812252}},
    AaveV3Base: {configs: {OTHERS: {}}, cache: {blockNumber: 26972112}},
    AaveV3Gnosis: {configs: {OTHERS: {}}, cache: {blockNumber: 38790856}},
    AaveV3Scroll: {configs: {OTHERS: {}}, cache: {blockNumber: 13728191}},
    AaveV3BNB: {configs: {OTHERS: {}}, cache: {blockNumber: 47050668}},
    AaveV3ZkSync: {configs: {OTHERS: {}}, cache: {blockNumber: 56750376}},
    AaveV3Linea: {configs: {OTHERS: {}}, cache: {blockNumber: 16370047}},
  },
};
