import {ConfigFile} from '../../generator/types';
export const config: ConfigFile = {
  rootOptions: {
    configFile:
      'src/20251013_AaveV3Avalanche_OnboardSUSDeAndUSDeToAaveV3AvalancheInstance/config.ts',
    force: true,
    author: 'Aave-chan Initiative',
    pools: ['AaveV3Avalanche'],
    title: 'Onboard sUSDe and USDe to Aave V3 Avalanche Instance',
    shortName: 'OnboardSUSDeAndUSDeToAaveV3AvalancheInstance',
    date: '20251013',
    discussion:
      'https://governance.aave.com/t/direct-to-aip-onboard-susde-and-usde-to-aave-v3-avalanche-instance/23081',
    snapshot: 'direct-to-AIP',
    votingNetwork: 'AVALANCHE',
  },
  poolOptions: {
    AaveV3Avalanche: {
      configs: {
        EMODES_CREATION: [
          {
            ltv: '89',
            liqThreshold: '92',
            liqBonus: '2',
            label: 'USDe/Stablecoin',
            collateralAssets: ['USDe'],
            borrowableAssets: ['USDC', 'USDt', 'GHO'],
          },
          {
            ltv: '89',
            liqThreshold: '91',
            liqBonus: '4',
            label: 'sUSDe/Stablecoin',
            collateralAssets: ['sUSDe'],
            borrowableAssets: ['USDe', 'USDC', 'USDt', 'GHO'],
          },
        ],
        ASSET_LISTING: [
          {
            assetSymbol: 'USDe',
            decimals: 18,
            priceFeed: '0x5b7810a910B4a878AaA4800a824E5E5796838009',
            ltv: '70',
            liqThreshold: '73',
            liqBonus: '8.5',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'ENABLED',
            flashloanable: 'ENABLED',
            borrowableInIsolation: 'DISABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '25',
            supplyCap: '50000000',
            borrowCap: '42500000',
            rateStrategyParams: {
              optimalUtilizationRate: '80',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '6.5',
              variableRateSlope2: '50',
            },
            asset: '0x5d3a1Ff2b6BAb83b63cd9AD0787074081a52ef34',
            admin: '0xac140648435d03f784879cd789130F22Ef588Fcd',
          },
          {
            assetSymbol: 'sUSDe',
            decimals: 18,
            priceFeed: '0x8Fb2db0A3b25db76B9BE2013751F8390ea8E5f0A',
            ltv: '70',
            liqThreshold: '73',
            liqBonus: '8.5',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'DISABLED',
            flashloanable: 'ENABLED',
            borrowableInIsolation: 'DISABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '45',
            supplyCap: '50000000',
            borrowCap: '1',
            rateStrategyParams: {
              optimalUtilizationRate: '45',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '10',
              variableRateSlope2: '300',
            },
            asset: '0x211Cc4DD073734dA055fbF44a2b4667d5E5fE5d2',
            admin: '0xac140648435d03f784879cd789130F22Ef588Fcd',
          },
        ],
      },
      cache: {blockNumber: 70259132},
    },
  },
};
