import {ConfigFile} from '../../generator/types';
export const config: ConfigFile = {
  rootOptions: {
    pools: ['AaveV3EthereumLido'],
    title: 'Lido Ethereum Instance Activation',
    shortName: 'LidoEthereumInstanceActivation',
    date: '20240720',
    author: 'Catapulta @catapulta_sh',
    discussion: 'https://governance.aave.com/t/arfc-deploy-a-lido-aave-v3-instance/18047',
    snapshot:
      'https://snapshot.org/#/aave.eth/proposal/0x9403b7f704ade0d6510591e4846fd85c84b19d134c0814511af914751ecfad5d',
    votingNetwork: 'POLYGON',
  },
  poolOptions: {
    AaveV3EthereumLido: {
      configs: {
        EMODES_UPDATES: [
          {
            eModeCategory: 1,
            ltv: '93.5',
            liqThreshold: '95.5',
            liqBonus: '1',
            priceSource: '0x0000000000000000000000000000000000000000',
            label: 'ETH Lido EMode',
          },
        ],
        ASSET_LISTING: [
          {
            assetSymbol: 'wstETH',
            decimals: 18,
            priceFeed: '0xB4aB0c94159bc2d8C133946E7241368fc2F2a010',
            ltv: '80',
            liqThreshold: '81',
            liqBonus: '6',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'ENABLED',
            flashloanable: 'ENABLED',
            stableRateModeEnabled: 'DISABLED',
            borrowableInIsolation: 'DISABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '5',
            supplyCap: '650000',
            borrowCap: '12000',
            rateStrategyParams: {
              optimalUtilizationRate: '45',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '3.5',
              variableRateSlope2: '85',
              stableRateSlope1: '0',
              stableRateSlope2: '0',
              baseStableRateOffset: '0',
              stableRateExcessOffset: '0',
              optimalStableToTotalDebtRatio: '0',
            },
            eModeCategory: '0',
            asset: '0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0',
          },
          {
            assetSymbol: 'WETH',
            decimals: 18,
            priceFeed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419',
            ltv: '82',
            liqThreshold: '83',
            liqBonus: '5',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'ENABLED',
            flashloanable: 'ENABLED',
            stableRateModeEnabled: 'DISABLED',
            borrowableInIsolation: 'DISABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '10',
            supplyCap: '900000',
            borrowCap: '810000',
            rateStrategyParams: {
              optimalUtilizationRate: '90',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '2.5',
              variableRateSlope2: '85',
              stableRateSlope1: '0',
              stableRateSlope2: '0',
              baseStableRateOffset: '0',
              stableRateExcessOffset: '0',
              optimalStableToTotalDebtRatio: '0',
            },
            eModeCategory: '0',
            asset: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
          },
        ],
      },
      cache: {blockNumber: 20347071},
    },
  },
};
