import {ConfigFile} from '../../generator/types';
export const config: ConfigFile = {
  rootOptions: {
    author: 'Aavechan Initiative @aci',
    pools: ['AaveV3Ethereum'],
    title: 'Listing PT Ethena May',
    shortName: 'ListingPTEthenaMay',
    date: '20260129',
    discussion:
      'https://governance.aave.com/t/direct-to-aip-onboard-usde-susde-may-expiry-pt-tokens-on-aave-v3-core-instance/23882',
    snapshot: 'direct-to-aip',
    votingNetwork: 'AVALANCHE',
  },
  poolOptions: {
    AaveV3Ethereum: {
      configs: {
        EMODES_CREATION: [
          {
            ltv: '87.2',
            liqThreshold: '89.2',
            liqBonus: '4.4',
            label: 'PT_USDe_7MAY2026__Stablecoins',
            collateralAssets: ['WETH', 'USDe', 'PT_USDe_5FEB2026'],
            borrowableAssets: ['USDC', 'USDT', 'USDe', 'USDtb'],
          },
          {
            ltv: '86.4',
            liqThreshold: '88.4',
            liqBonus: '5.5',
            label: 'PT_sUSDe_7MAY2026',
            collateralAssets: ['wstETH', 'sUSDe', 'PT_sUSDE_5FEB2026'],
            borrowableAssets: ['USDC', 'USDT', 'USDe', 'USDtb'],
          },
        ],
        ASSET_LISTING: [
          {
            assetSymbol: 'PT_USDe_7MAY2026',
            decimals: 18,
            priceFeed: '0x0a72df02CE3E4185b6CEDf561f0AE651E9BeE235',
            ltv: '0',
            liqThreshold: '0',
            liqBonus: '0',
            debtCeiling: '1',
            liqProtocolFee: '10',
            enabledToBorrow: 'DISABLED',
            flashloanable: 'ENABLED',
            borrowableInIsolation: 'DISABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '45',
            supplyCap: '30000000',
            borrowCap: '1',
            rateStrategyParams: {
              optimalUtilizationRate: '45',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '10',
              variableRateSlope2: '300',
            },
            asset: '0xaebf0bb9f57e89260d57f31af34eb58657d96ce0',
            admin: '0xac140648435d03f784879cd789130F22Ef588Fcd',
          },
          {
            assetSymbol: 'PT_sUSDe_7MAY2026',
            decimals: 18,
            priceFeed: '0xa0dc0249c32fa79e8B9b17c735908a60b1141B40',
            ltv: '0',
            liqThreshold: '0',
            liqBonus: '0',
            debtCeiling: '1',
            liqProtocolFee: '10',
            enabledToBorrow: 'DISABLED',
            flashloanable: 'ENABLED',
            borrowableInIsolation: 'DISABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '45',
            supplyCap: '70000000',
            borrowCap: '1',
            rateStrategyParams: {
              optimalUtilizationRate: '45',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '10',
              variableRateSlope2: '300',
            },
            asset: '0x3de0ff76e8b528c092d47b9dac775931cef80f49',
            admin: '0xac140648435d03f784879cd789130F22Ef588Fcd',
          },
        ],
      },
      cache: {blockNumber: 24339431},
    },
  },
};
