import {ConfigFile} from '../../generator/types';
export const config: ConfigFile = {
  rootOptions: {
    author: 'BGD Labs @bgdlabs',
    pools: [
      'AaveV3Ethereum',
      'AaveV3EthereumLido',
      'AaveV3EthereumEtherFi',
      'AaveV3Polygon',
      'AaveV3Avalanche',
      'AaveV3Optimism',
      'AaveV3Arbitrum',
      'AaveV3Metis',
      'AaveV3Base',
      'AaveV3Gnosis',
      'AaveV3Scroll',
      'AaveV3BNB',
      'AaveV3ZkSync',
      'AaveV3Linea',
      'AaveV3Celo',
      'AaveV3Sonic',
      'AaveV3Soneium',
    ],
    title: 'Upgrade Aave instances to v3.5',
    shortName: 'UpgradeAaveInstancesToV35',
    date: '20250722',
    discussion: 'https://governance.aave.com/t/direct-to-aip-bgd-aave-v3-5-v3-4-part-2/22639/1',
    snapshot: '',
    votingNetwork: 'POLYGON',
  },
  poolOptions: {
    AaveV3Ethereum: {configs: {OTHERS: {}}, cache: {blockNumber: 22977349}},
    AaveV3EthereumLido: {configs: {OTHERS: {}}, cache: {blockNumber: 22977349}},
    AaveV3EthereumEtherFi: {configs: {OTHERS: {}}, cache: {blockNumber: 22977349}},
    AaveV3Polygon: {configs: {OTHERS: {}}, cache: {blockNumber: 74285543}},
    AaveV3Avalanche: {configs: {OTHERS: {}}, cache: {blockNumber: 65909138}},
    AaveV3Optimism: {configs: {OTHERS: {}}, cache: {blockNumber: 138810181}},
    AaveV3Arbitrum: {configs: {OTHERS: {}}, cache: {blockNumber: 360504961}},
    AaveV3Metis: {configs: {OTHERS: {}}, cache: {blockNumber: 20873480}},
    AaveV3Base: {configs: {OTHERS: {}}, cache: {blockNumber: 33214896}},
    AaveV3Gnosis: {configs: {OTHERS: {}}, cache: {blockNumber: 41223005}},
    AaveV3Scroll: {configs: {OTHERS: {}}, cache: {blockNumber: 17500340}},
    AaveV3BNB: {configs: {OTHERS: {}}, cache: {blockNumber: 54961617}},
    AaveV3ZkSync: {configs: {OTHERS: {}}, cache: {blockNumber: 63236506}},
    AaveV3Linea: {configs: {OTHERS: {}}, cache: {blockNumber: 21166376}},
    AaveV3Celo: {configs: {OTHERS: {}}, cache: {blockNumber: 41318392}},
    AaveV3Sonic: {configs: {OTHERS: {}}, cache: {blockNumber: 39753263}},
    AaveV3Soneium: {configs: {OTHERS: {}}, cache: {blockNumber: 10042200}},
  },
};
