import {ConfigFile} from '../../generator/types';
export const config: ConfigFile = {
  rootOptions: {
    pools: ['AaveV3ZkSync'],
    title: 'Aave v3 zkSync Activation',
    shortName: 'AaveV3ZkSyncActivation',
    date: '20240805',
    author: 'BGD Labs (@bgdlabs)',
    discussion: 'https://governance.aave.com/t/arfc-deployment-of-aave-on-zksync/17937',
    snapshot:
      'https://snapshot.org/#/aave.eth/proposal/0xb74537a0528f484e9cc76d8c7931eedef7b6290e7d2dc725b2c98e623a214f95',
    votingNetwork: 'POLYGON',
  },
  poolOptions: {
    AaveV3ZkSync: {
      configs: {
        ASSET_LISTING: [
          {
            assetSymbol: 'USDC',
            decimals: 6,
            priceFeed: '0xA715ED3eC1C078EEf8437Cf717Cf76004f29eAED',
            ltv: '75',
            liqThreshold: '78',
            liqBonus: '5',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'ENABLED',
            flashloanable: 'ENABLED',
            stableRateModeEnabled: 'DISABLED',
            borrowableInIsolation: 'ENABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '10',
            supplyCap: '1000000',
            borrowCap: '900000',
            rateStrategyParams: {
              optimalUtilizationRate: '90',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '9',
              variableRateSlope2: '75',
            },
            eModeCategory: '0',
            asset: '0x1d17CBcF0D6D143135aE902365D2E5e2A16538D4',
          },
          {
            assetSymbol: 'USDT',
            decimals: 6,
            priceFeed: '0x336EC4bcb65C1A141318fBd3f8E7379c085E8B15',
            ltv: '75',
            liqThreshold: '78',
            liqBonus: '5',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'ENABLED',
            flashloanable: 'ENABLED',
            stableRateModeEnabled: 'DISABLED',
            borrowableInIsolation: 'ENABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '10',
            supplyCap: '3000000',
            borrowCap: '2700000',
            rateStrategyParams: {
              optimalUtilizationRate: '90',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '9',
              variableRateSlope2: '75',
            },
            eModeCategory: '0',
            asset: '0x493257fD37EDB34451f62EDf8D2a0C418852bA4C',
          },
          {
            assetSymbol: 'WETH',
            decimals: 18,
            priceFeed: '0x6D41d1dc818112880b40e26BD6FD347E41008eDA',
            ltv: '75',
            liqThreshold: '78',
            liqBonus: '6',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'ENABLED',
            flashloanable: 'ENABLED',
            stableRateModeEnabled: 'DISABLED',
            borrowableInIsolation: 'DISABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '15',
            supplyCap: '1000',
            borrowCap: '800',
            rateStrategyParams: {
              optimalUtilizationRate: '80',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '3.3',
              variableRateSlope2: '80',
            },
            eModeCategory: '0',
            asset: '0x5AEa5775959fBC2557Cc8789bC1bf90A239D9a91',
          },
          {
            assetSymbol: 'wstETH',
            decimals: 18,
            priceFeed: '0x624FEc7DDeb62Dcbce1fc456D7cc5c6A47cC69aF',
            ltv: '71',
            liqThreshold: '76',
            liqBonus: '7',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'ENABLED',
            flashloanable: 'ENABLED',
            stableRateModeEnabled: 'DISABLED',
            borrowableInIsolation: 'DISABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '15',
            supplyCap: '500',
            borrowCap: '50',
            rateStrategyParams: {
              optimalUtilizationRate: '45',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '4.5',
              variableRateSlope2: '80',
            },
            eModeCategory: '0',
            asset: '0x703b52F2b28fEbcB60E1372858AF5b18849FE867',
          },
          {
            assetSymbol: 'ZK',
            decimals: 18,
            priceFeed: '0xD1ce60dc8AE060DDD17cA8716C96f193bC88DD13',
            ltv: '40',
            liqThreshold: '45',
            liqBonus: '10',
            debtCeiling: '1000000',
            liqProtocolFee: '20',
            enabledToBorrow: 'ENABLED',
            flashloanable: 'ENABLED',
            stableRateModeEnabled: 'DISABLED',
            borrowableInIsolation: 'DISABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '20',
            supplyCap: '24000000',
            borrowCap: '10000000',
            rateStrategyParams: {
              optimalUtilizationRate: '45',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '9',
              variableRateSlope2: '300',
            },
            eModeCategory: '0',
            asset: '0x5a7d6b2f92c77fad6ccabd7ee0624e64907eaf3e',
          },
        ],
      },
      cache: {blockNumber: 40901979},
    },
  },
};
