[profile.default]
src = 'src'
test = 'tests'
script = 'scripts'
solc = '0.8.27'
optimizer = true
optimizer_runs = 200
out = 'out'
bytecode_hash = 'none'
libs = ['lib']
remappings = []
ffi = true
fs_permissions = [
  { access = "write", path = "./reports" },
  { access = "read", path = "./zkout" },
]
evm_version = 'london'
cache_path = 'cache/london'

[profile.zksync]
src = 'zksync'
test = 'zksync'
libs = ['lib']
solc = '0.8.22'
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "write", path = "./reports" }]
ffi = true
evm_version = 'shanghai'
cache_path = 'cache/shanghai'

[profile.zksync.zksync]
bytecode_hash = 'none'
compile = true
fallback_oz = true
mode = '3'
zksolc = '1.5.13'

[profile.test]
evm_version = 'cancun'
cache_path = 'cache/cancun'

[profile.deploy]
evm_version = 'london' # due to linea
cache_path = 'cache/london'

[profile.sonic]
evm_version = 'cancun'
cache_path = 'cache/cancun'

[profile.soneium]
evm_version = 'cancun'
cache_path = 'cache/cancun'

[profile.celo]
evm_version = 'cancun'
cache_path = 'cache/cancun'

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
optimism = "${RPC_OPTIMISM}"
avalanche = "${RPC_AVALANCHE}"
polygon = "${RPC_POLYGON}"
arbitrum = "${RPC_ARBITRUM}"
fantom = "${RPC_FANTOM}"
harmony = "${RPC_HARMONY}"
metis = "${RPC_METIS}"
base = "${RPC_BASE}"
zkevm = "${RPC_ZKEVM}"
gnosis = "${RPC_GNOSIS}"
bnb = "${RPC_BNB}"
scroll = "${RPC_SCROLL}"
zksync = "${RPC_ZKSYNC}"
linea = "${RPC_LINEA}"
celo = "${RPC_CELO}"
sonic = "${RPC_SONIC}"
soneium = "${RPC_SONEIUM}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
