import {ConfigFile} from '../../generator/types';
export const config: ConfigFile = {
  rootOptions: {
    author: 'BGD Labs @bgdlabs',
    pools: [
      'AaveV3Ethereum',
      'AaveV3Polygon',
      'AaveV3Avalanche',
      'AaveV3Optimism',
      'AaveV3Arbitrum',
      'AaveV3Metis',
      'AaveV3Base',
      'AaveV3Gnosis',
      'AaveV3Scroll',
      'AaveV3BNB',
      'AaveV3ZkSync',
      'AaveV3Linea',
    ],
    title: 'Collector upgrade',
    shortName: 'CollectorUpgrade',
    date: '20250124',
    discussion: 'https://governance.aave.com/t/technical-maintenance-proposals/15274/63',
    snapshot: '',
    votingNetwork: 'POLYGON',
  },
  poolOptions: {
    AaveV3Ethereum: {configs: {OTHERS: {}}, cache: {blockNumber: 21693718}},
    AaveV3Polygon: {configs: {OTHERS: {}}, cache: {blockNumber: 67083310}},
    AaveV3Avalanche: {configs: {OTHERS: {}}, cache: {blockNumber: 56282481}},
    AaveV3Optimism: {configs: {OTHERS: {}}, cache: {blockNumber: 131057593}},
    AaveV3Arbitrum: {configs: {OTHERS: {}}, cache: {blockNumber: 298749428}},
    AaveV3Metis: {configs: {OTHERS: {}}, cache: {blockNumber: 19553469}},
    AaveV3Base: {configs: {OTHERS: {}}, cache: {blockNumber: 25462310}},
    AaveV3Gnosis: {configs: {OTHERS: {}}, cache: {blockNumber: 38202526}},
    AaveV3Scroll: {configs: {OTHERS: {}}, cache: {blockNumber: 12931198}},
    AaveV3BNB: {configs: {OTHERS: {}}, cache: {blockNumber: 46044224}},
    AaveV3ZkSync: {configs: {OTHERS: {}}, cache: {blockNumber: 54433709}},
    AaveV3Linea: {configs: {OTHERS: {}}, cache: {blockNumber: 14978552}},
  },
};
