import {ConfigFile} from '../../generator/types';
export const config: ConfigFile = {
  rootOptions: {
    pools: [
      'AaveV3Ethereum',
      'AaveV3Polygon',
      'AaveV3Avalanche',
      'AaveV3Optimism',
      'AaveV3Arbitrum',
      'AaveV3Metis',
      'AaveV3Base',
      'AaveV3Gnosis',
      'AaveV3Scroll',
      'AaveV3BNB',
      'AaveV3ZkSync',
      'AaveV3Linea',
      'AaveV3Celo',
      'AaveV3Sonic',
      'AaveV3Soneium',
      'AaveV3Plasma',
      'AaveV3Mantle',
      'AaveV3MegaEth',
      'AaveV3XLayer',
    ],
    title: 'Maintenance: Grant AL RETRY_ROLE on a.DI',
    shortName: 'MaintenanceGrantALRETRY_ROLEOnADI',
    date: '20260603',
    author: 'Aave Labs',
    discussion:
      'https://governance.aave.com/t/direct-to-aip-grant-aave-labs-retry-role-on-a-di/25020',
    snapshot: 'direct-to-aip',
    votingNetwork: 'AVALANCHE',
  },
  poolOptions: {
    AaveV3Ethereum: {configs: {OTHERS: {}}, cache: {blockNumber: 25236865}},
    AaveV3Polygon: {configs: {OTHERS: {}}, cache: {blockNumber: 87857137}},
    AaveV3Avalanche: {configs: {OTHERS: {}}, cache: {blockNumber: 87078183}},
    AaveV3Optimism: {configs: {OTHERS: {}}, cache: {blockNumber: 152445468}},
    AaveV3Arbitrum: {configs: {OTHERS: {}}, cache: {blockNumber: 469618015}},
    AaveV3Metis: {configs: {OTHERS: {}}, cache: {blockNumber: 22731449}},
    AaveV3Base: {configs: {OTHERS: {}}, cache: {blockNumber: 46850185}},
    AaveV3Gnosis: {configs: {OTHERS: {}}, cache: {blockNumber: 46506840}},
    AaveV3Scroll: {configs: {OTHERS: {}}, cache: {blockNumber: 33939451}},
    AaveV3BNB: {configs: {OTHERS: {}}, cache: {blockNumber: 102072793}},
    AaveV3ZkSync: {configs: {OTHERS: {}}, cache: {blockNumber: 70419537}},
    AaveV3Linea: {configs: {OTHERS: {}}, cache: {blockNumber: 30887170}},
    AaveV3Celo: {configs: {OTHERS: {}}, cache: {blockNumber: 68588965}},
    AaveV3Sonic: {configs: {OTHERS: {}}, cache: {blockNumber: 72292126}},
    AaveV3Soneium: {configs: {OTHERS: {}}, cache: {blockNumber: 23677487}},
    AaveV3Plasma: {configs: {OTHERS: {}}, cache: {blockNumber: 23549834}},
    AaveV3Mantle: {configs: {OTHERS: {}}, cache: {blockNumber: 96179708}},
    AaveV3MegaEth: {configs: {OTHERS: {}}, cache: {blockNumber: 17692718}},
    AaveV3XLayer: {configs: {OTHERS: {}}, cache: {blockNumber: 61720695}},
  },
};
