import {ConfigFile} from '../../generator/types';
export const config: ConfigFile = {
  rootOptions: {
    pools: [
      'AaveV3Ethereum',
      'AaveV3Polygon',
      'AaveV3Avalanche',
      'AaveV3Optimism',
      'AaveV3Arbitrum',
      'AaveV3Metis',
      'AaveV3Base',
      'AaveV3Gnosis',
      'AaveV3Scroll',
      'AaveV3BNB',
      'AaveV3ZkSync',
      'AaveV3Linea',
      'AaveV3Celo',
      'AaveV3Sonic',
      'AaveV3Soneium',
      'AaveV3Plasma',
      'AaveV3Mantle',
      'AaveV3MegaEth',
      'AaveV3XLayer',
    ],
    title: 'Maintenance: Grant AL RETRY_ROLE on a.DI',
    shortName: 'MaintenanceGrantALRETRY_ROLEOnADI',
    date: '20260603',
    author: 'Aave Labs',
    discussion:
      'https://governance.aave.com/t/direct-to-aip-grant-aave-labs-retry-role-on-a-di/25020',
    snapshot: 'direct-to-aip',
    votingNetwork: 'AVALANCHE',
  },
  poolOptions: {
    AaveV3Ethereum: {configs: {OTHERS: {}}, cache: {blockNumber: 25331064}},
    AaveV3Polygon: {configs: {OTHERS: {}}, cache: {blockNumber: 88613159}},
    AaveV3Avalanche: {configs: {OTHERS: {}}, cache: {blockNumber: 88166147}},
    AaveV3Optimism: {configs: {OTHERS: {}}, cache: {blockNumber: 153012974}},
    AaveV3Arbitrum: {configs: {OTHERS: {}}, cache: {blockNumber: 474138999}},
    AaveV3Metis: {configs: {OTHERS: {}}, cache: {blockNumber: 22769592}},
    AaveV3Base: {configs: {OTHERS: {}}, cache: {blockNumber: 47417690}},
    AaveV3Gnosis: {configs: {OTHERS: {}}, cache: {blockNumber: 46728410}},
    AaveV3Scroll: {configs: {OTHERS: {}}, cache: {blockNumber: 34100777}},
    AaveV3BNB: {configs: {OTHERS: {}}, cache: {blockNumber: 104592530}},
    AaveV3ZkSync: {configs: {OTHERS: {}}, cache: {blockNumber: 70419537}},
    AaveV3Linea: {configs: {OTHERS: {}}, cache: {blockNumber: 31054604}},
    AaveV3Celo: {configs: {OTHERS: {}}, cache: {blockNumber: 69723976}},
    AaveV3Sonic: {configs: {OTHERS: {}}, cache: {blockNumber: 74071830}},
    AaveV3Soneium: {configs: {OTHERS: {}}, cache: {blockNumber: 24244992}},
    AaveV3Plasma: {configs: {OTHERS: {}}, cache: {blockNumber: 24684836}},
    AaveV3Mantle: {configs: {OTHERS: {}}, cache: {blockNumber: 96747210}},
    AaveV3MegaEth: {configs: {OTHERS: {}}, cache: {blockNumber: 18827721}},
    AaveV3XLayer: {configs: {OTHERS: {}}, cache: {blockNumber: 62855697}},
  },
};
