import {ConfigFile} from '../../generator/types';
export const config: ConfigFile = {
  rootOptions: {
    configFile: 'tmp.ts',
    force: true,
    author: 'Aave_chan Initiative',
    pools: ['AaveV3Plasma'],
    title: 'Onboard sUSDe and USDe January expiry PT tokens on Aave V3 Plasma Instance',
    shortName: 'OnboardSUSDeAndUSDeJanuaryExpiryPTTokensOnAaveV3PlasmaInstance',
    date: '20251007',
    discussion:
      'https://governance.aave.com/t/direct-to-aip-onboard-susde-and-usde-january-expiry-pt-tokens-on-aave-v3-plasma-instance/23196',
    snapshot: 'direct-to-aip',
    votingNetwork: 'AVALANCHE',
  },
  poolOptions: {
    AaveV3Plasma: {
      configs: {
        EMODES_CREATION: [
          {
            ltv: '85.4',
            liqThreshold: '87.4',
            liqBonus: '4.9',
            label: 'PT_USDe_15JAN2026/Stablecoin',
            collateralAssets: ['PT_USDe_15JAN2026'],
            borrowableAssets: ['USDT0', 'USDe'],
          },
          {
            ltv: '86.2',
            liqThreshold: '88.2',
            liqBonus: '3.9',
            label: 'PT_USDe_15JAN2026/USDe',
            collateralAssets: ['PT_USDe_15JAN2026'],
            borrowableAssets: ['USDe'],
          },
          {
            ltv: '83.9',
            liqThreshold: '85.9',
            liqBonus: '6',
            label: 'PT_sUSDe_15JAN2026/Stablecoin',
            collateralAssets: ['PT_sUSDe_15JAN2026'],
            borrowableAssets: ['USDT0', 'USDe'],
          },
          {
            ltv: '84.5',
            liqThreshold: '86.5',
            liqBonus: '5.2',
            label: 'PT_sUSDe_15JAN2026/USDe',
            collateralAssets: ['PT_sUSDe_15JAN2026'],
            borrowableAssets: ['USDe'],
          },
        ],
        ASSET_LISTING: [
          {
            assetSymbol: 'PT_USDe_15JAN2026',
            decimals: 18,
            priceFeed: '0x30cb6ff8649Cc02cEa91971D4730EebeD5A8D2F1',
            ltv: '0.05',
            liqThreshold: '0.1',
            liqBonus: '7.5',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'DISABLED',
            flashloanable: 'ENABLED',
            borrowableInIsolation: 'DISABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '45',
            supplyCap: '200000000',
            borrowCap: '1',
            rateStrategyParams: {
              optimalUtilizationRate: '45',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '10',
              variableRateSlope2: '300',
            },
            asset: '0x93B544c330F60A2aa05ceD87aEEffB8D38FD8c9a',
            admin: '0xac140648435d03f784879cd789130F22Ef588Fcd',
          },
          {
            assetSymbol: 'PT_sUSDE_15JAN2026',
            decimals: 18,
            priceFeed: '0x3eca1c7836eA09DB3dc85be7B5526Ce80E2609a1',
            ltv: '0.05',
            liqThreshold: '0.1',
            liqBonus: '7.5',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'DISABLED',
            flashloanable: 'ENABLED',
            borrowableInIsolation: 'DISABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '45',
            supplyCap: '200000000',
            borrowCap: '1',
            rateStrategyParams: {
              optimalUtilizationRate: '45',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '10',
              variableRateSlope2: '300',
            },
            asset: '0x02FCC4989B4C9D435b7ceD3fE1Ba4CF77BBb5Dd8',
            admin: '0xac140648435d03f784879cd789130F22Ef588Fcd',
          },
        ],
      },
      cache: {blockNumber: 2942866},
    },
  },
};
