import {ConfigFile} from '../../generator/types';
export const config: ConfigFile = {
  rootOptions: {
    configFile: 'src/20260117_AaveV3Mantle_AaveV36MantleActivation/config.ts',
    pools: ['AaveV3Mantle'],
    title: 'Aave V3.6 Mantle Activation',
    shortName: 'AaveV36MantleActivation',
    date: '20260117',
    author: 'BGD Labs (@bgdlabs)',
    discussion: 'https://governance.aave.com/t/arfc-deploy-aave-v3-on-mantle/20542/12',
    snapshot:
      'https://snapshot.org/#/s:aavedao.eth/proposal/0x2f9378770f1838f0ea8d483239af1530c9fbea98d648e0b11e4647dcb722d119',
    votingNetwork: 'AVALANCHE',
  },
  poolOptions: {
    AaveV3Mantle: {
      configs: {
        ASSET_LISTING: [
          {
            assetSymbol: 'WETH',
            decimals: 18,
            priceFeed: '0x5bc7Cf88EB131DB18b5d7930e793095140799aD5',
            ltv: '80.5',
            liqThreshold: '83',
            liqBonus: '5.5',
            debtCeiling: '30000000',
            liqProtocolFee: '10',
            enabledToBorrow: 'ENABLED',
            flashloanable: 'ENABLED',
            borrowableInIsolation: 'DISABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '15',
            supplyCap: '30000',
            borrowCap: '28000',
            rateStrategyParams: {
              optimalUtilizationRate: '90',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '2.5',
              variableRateSlope2: '8',
            },
            asset: '0xdEAddEaDdeadDEadDEADDEAddEADDEAddead1111',
            admin: '',
          },
          {
            assetSymbol: 'WMNT',
            decimals: 18,
            priceFeed: '0xD97F20bEbeD74e8144134C4b148fE93417dd0F96',
            ltv: '40',
            liqThreshold: '45',
            liqBonus: '10',
            debtCeiling: '2000000',
            liqProtocolFee: '10',
            enabledToBorrow: 'DISABLED',
            flashloanable: 'ENABLED',
            borrowableInIsolation: 'DISABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '20',
            supplyCap: '5000000',
            borrowCap: '1',
            rateStrategyParams: {
              optimalUtilizationRate: '90',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '5',
              variableRateSlope2: '20',
            },
            asset: '0x78c1b0c915c4faa5fffa6cabf0219da63d7f4cb8',
            admin: '',
          },
          {
            assetSymbol: 'USDT0',
            decimals: 6,
            priceFeed: '0xFA5dEcEd7cdCEAB065addd0E32D9527ABd1069Ee',
            ltv: '0',
            liqThreshold: '0',
            liqBonus: '0',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'ENABLED',
            flashloanable: 'ENABLED',
            borrowableInIsolation: 'ENABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '10',
            supplyCap: '50000000',
            borrowCap: '47000000',
            rateStrategyParams: {
              optimalUtilizationRate: '90',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '5',
              variableRateSlope2: '10',
            },
            asset: '0x779ded0c9e1022225f8e0630b35a9b54be713736',
            admin: '',
          },
          {
            assetSymbol: 'USDC',
            decimals: 6,
            priceFeed: '0x3876fb349c14613e0633b5cae08c4e3b1d4904fb',
            ltv: '0',
            liqThreshold: '0',
            liqBonus: '0',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'ENABLED',
            flashloanable: 'ENABLED',
            borrowableInIsolation: 'ENABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '10',
            supplyCap: '10000000',
            borrowCap: '9500000',
            rateStrategyParams: {
              optimalUtilizationRate: '90',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '5',
              variableRateSlope2: '10',
            },
            asset: '0x09bc4e0d864854c6afb6eb9a9cdf58ac190d0df9',
            admin: '',
          },
          {
            assetSymbol: 'USDe',
            decimals: 18,
            priceFeed: '0xFA5dEcEd7cdCEAB065addd0E32D9527ABd1069Ee',
            ltv: '0',
            liqThreshold: '0',
            liqBonus: '0',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'ENABLED',
            flashloanable: 'ENABLED',
            borrowableInIsolation: 'ENABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '10',
            supplyCap: '20000000',
            borrowCap: '17500000',
            rateStrategyParams: {
              optimalUtilizationRate: '85',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '5.25',
              variableRateSlope2: '12',
            },
            asset: '0x5d3a1ff2b6bab83b63cd9ad0787074081a52ef34',
            admin: '',
          },
          {
            assetSymbol: 'sUSDe',
            decimals: 18,
            priceFeed: '0x8b47ec48ac560793861d94a997d020872c1ce3f5',
            ltv: '0',
            liqThreshold: '0',
            liqBonus: '0',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'DISABLED',
            flashloanable: 'ENABLED',
            borrowableInIsolation: 'DISABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '20',
            supplyCap: '20000000',
            borrowCap: '1',
            rateStrategyParams: {
              optimalUtilizationRate: '90',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '5',
              variableRateSlope2: '20',
            },
            asset: '0x211cc4dd073734da055fbf44a2b4667d5e5fe5d2',
            admin: '',
          },
          {
            assetSymbol: 'FBTC',
            decimals: 8,
            priceFeed: '0x7db2275279F52D0914A481e14c4Ce5a59705A25b',
            ltv: '0',
            liqThreshold: '0',
            liqBonus: '0',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'DISABLED',
            flashloanable: 'ENABLED',
            borrowableInIsolation: 'DISABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '20',
            supplyCap: '50',
            borrowCap: '1',
            rateStrategyParams: {
              optimalUtilizationRate: '90',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '5',
              variableRateSlope2: '20',
            },
            asset: '0xC96dE26018A54D51c097160568752c4E3BD6C364',
            admin: '',
          },
          {
            assetSymbol: 'syrupUSDT',
            decimals: 6,
            priceFeed: '0xcf1700ee060ab65fa16d5f44a6fbf16721eb0d9b',
            ltv: '0',
            liqThreshold: '0',
            liqBonus: '0',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'DISABLED',
            flashloanable: 'ENABLED',
            borrowableInIsolation: 'DISABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '20',
            supplyCap: '70000000',
            borrowCap: '1',
            rateStrategyParams: {
              optimalUtilizationRate: '90',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '5',
              variableRateSlope2: '20',
            },
            asset: '0x051665f2455116e929b9972c36d23070F5054Ce0',
            admin: '',
          },
          {
            assetSymbol: 'wrsETH',
            decimals: 18,
            priceFeed: '0xfed794060d37391d966f931b9509378063c5b0fb',
            ltv: '0',
            liqThreshold: '0',
            liqBonus: '0',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'DISABLED',
            flashloanable: 'ENABLED',
            borrowableInIsolation: 'DISABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '20',
            supplyCap: '18000',
            borrowCap: '1',
            rateStrategyParams: {
              optimalUtilizationRate: '90',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '5',
              variableRateSlope2: '20',
            },
            asset: '0x93e855643e940D025bE2e529272e4Dbd15a2Cf74',
            admin: '',
          },
        ],
      },
      cache: {blockNumber: 90260247},
    },
  },
};
