import {ConfigFile} from '../../generator/types';
export const config: ConfigFile = {
  rootOptions: {
    author: 'BGD Labs @bgdlabs',
    pools: [
      'AaveV3Ethereum',
      'AaveV3Polygon',
      'AaveV3Avalanche',
      'AaveV3BNB',
      'AaveV3Base',
      'AaveV3Gnosis',
      'AaveV3Optimism',
      'AaveV3Arbitrum',
      'AaveV3Metis',
      'AaveV3Scroll',
    ],
    title: 'Update a.DI implementation and CCIP adapters',
    shortName: 'UpdateADIImplementationAndCCIPAdapters',
    date: '20240313',
    discussion: '',
    snapshot: '',
  },
  poolOptions: {
    AaveV3Ethereum: {configs: {OTHERS: {}}, cache: {blockNumber: 19424932}},
    AaveV3Polygon: {configs: {OTHERS: {}}, cache: {blockNumber: 54601669}},
    AaveV3Avalanche: {configs: {OTHERS: {}}, cache: {blockNumber: 42840161}},
    AaveV3BNB: {configs: {OTHERS: {}}, cache: {blockNumber: 36928161}},
    AaveV3Base: {configs: {OTHERS: {}}, cache: {blockNumber: 36928161}},
    AaveV3Gnosis: {configs: {OTHERS: {}}, cache: {blockNumber: 36928161}},
    AaveV3Optimism: {configs: {OTHERS: {}}, cache: {blockNumber: 36928161}},
    AaveV3Arbitrum: {configs: {OTHERS: {}}, cache: {blockNumber: 36928161}},
    AaveV3Metis: {configs: {OTHERS: {}}, cache: {blockNumber: 36928161}},
    AaveV3Scroll: {configs: {OTHERS: {}}, cache: {blockNumber: 36928161}},
  },
};
