import {ConfigFile} from '../../generator/types';
export const config: ConfigFile = {
  rootOptions: {
    pools: [
      'AaveV3Ethereum',
      'AaveV3EthereumLido',
      'AaveV3Polygon',
      'AaveV3Avalanche',
      'AaveV3Optimism',
      'AaveV3Arbitrum',
      'AaveV3Metis',
      'AaveV3Base',
      'AaveV3Gnosis',
      'AaveV3Scroll',
      'AaveV3BNB',
      'AaveV3ZkSync',
      'AaveV3Linea',
      'AaveV3Celo',
      'AaveV3Sonic',
    ],
    title: 'Discount Rate Risk Oracle Activation and update manual AGRS',
    shortName: 'PendlePTDiscountRateRiskOracleActivation',
    date: '20250606',
    author: 'BGD Labs (@bgdlabs)',
    discussion: 'https://governance.aave.com/t/technical-maintenance-proposals/15274/93',
    snapshot: '',
    votingNetwork: 'POLYGON',
  },
  poolOptions: {
    AaveV3Ethereum: {configs: {OTHERS: {}}, cache: {blockNumber: 22645222}},
    AaveV3EthereumLido: {configs: {OTHERS: {}}, cache: {blockNumber: 22645222}},
    AaveV3Polygon: {configs: {OTHERS: {}}, cache: {blockNumber: 72431826}},
    AaveV3Avalanche: {configs: {OTHERS: {}}, cache: {blockNumber: 63393286}},
    AaveV3Optimism: {configs: {OTHERS: {}}, cache: {blockNumber: 136805087}},
    AaveV3Arbitrum: {configs: {OTHERS: {}}, cache: {blockNumber: 344491817}},
    AaveV3Metis: {configs: {OTHERS: {}}, cache: {blockNumber: 20565245}},
    AaveV3Base: {configs: {OTHERS: {}}, cache: {blockNumber: 31209804}},
    AaveV3Gnosis: {configs: {OTHERS: {}}, cache: {blockNumber: 40443833}},
    AaveV3Scroll: {configs: {OTHERS: {}}, cache: {blockNumber: 16265405}},
    AaveV3BNB: {configs: {OTHERS: {}}, cache: {blockNumber: 50976645}},
    AaveV3ZkSync: {configs: {OTHERS: {}}, cache: {blockNumber: 61387801}},
    AaveV3Linea: {configs: {OTHERS: {}}, cache: {blockNumber: 19728042}},
    AaveV3Celo: {configs: {OTHERS: {}}, cache: {blockNumber: 37308210}},
    AaveV3Sonic: {configs: {OTHERS: {}}, cache: {blockNumber: 32243823}},
  },
};
