import {ConfigFile} from '../../generator/types';
export const config: ConfigFile = {
  rootOptions: {
    pools: [
      'AaveV3Ethereum',
      'AaveV3EthereumLido',
      'AaveV3Polygon',
      'AaveV3Avalanche',
      'AaveV3Optimism',
      'AaveV3Arbitrum',
      'AaveV3Base',
      'AaveV3Scroll',
      'AaveV3BNB',
      'AaveV3Linea',
      'AaveV3Sonic',
    ],
    title: 'Finance Steward Deployment: Pool Exposure Module',
    shortName: 'FinanceStewardDeploymentPoolExposureModule',
    date: '20250319',
    author: '@TokenLogic',
    discussion: '',
    snapshot: '',
    votingNetwork: 'POLYGON',
  },
  poolOptions: {
    AaveV3Ethereum: {configs: {OTHERS: {}}, cache: {blockNumber: 22080648}},
    AaveV3EthereumLido: {configs: {OTHERS: {}}, cache: {blockNumber: 22080648}},
    AaveV3Polygon: {configs: {OTHERS: {}}, cache: {blockNumber: 69238268}},
    AaveV3Avalanche: {configs: {OTHERS: {}}, cache: {blockNumber: 58941868}},
    AaveV3Optimism: {configs: {OTHERS: {}}, cache: {blockNumber: 133392643}},
    AaveV3Arbitrum: {configs: {OTHERS: {}}, cache: {blockNumber: 319049030}},
    AaveV3Base: {configs: {OTHERS: {}}, cache: {blockNumber: 27797204}},
    AaveV3Scroll: {configs: {OTHERS: {}}, cache: {blockNumber: 14111144}},
    AaveV3BNB: {configs: {OTHERS: {}}, cache: {blockNumber: 47600798}},
    AaveV3Linea: {configs: {OTHERS: {}}, cache: {blockNumber: 17122442}},
    AaveV3Sonic: {configs: {OTHERS: {}}, cache: {blockNumber: 14619228}},
  },
};
