import {ConfigFile} from '../../generator/types';
export const config: ConfigFile = {
  rootOptions: {
    pools: [
      'AaveV3Ethereum',
      'AaveV3Arbitrum',
      'AaveV3Avalanche',
      'AaveV3Base',
      'AaveV3Gnosis',
      'AaveV3Mantle',
      'AaveV3Plasma',
      'AaveV3Monad',
      'AaveV3XLayer',
      'AaveV3Ink',
    ],
    title: 'Remote GSM Launch: XLayer',
    shortName: 'RemoteGSMLaunchXLayer',
    date: '20260729',
    author: 'TokenLogic',
    discussion: 'TODO_FORUM_POST_PENDING',
    snapshot: 'TODO_SNAPSHOT_PENDING',
    votingNetwork: 'AVALANCHE',
  },
  poolOptions: {
    AaveV3Ethereum: {configs: {}, cache: {blockNumber: 25731136}},
    AaveV3Arbitrum: {configs: {OTHERS: {}}, cache: {blockNumber: 493392463}},
    AaveV3Avalanche: {configs: {OTHERS: {}}, cache: {blockNumber: 92551188}},
    AaveV3Base: {configs: {OTHERS: {}}, cache: {blockNumber: 49827271}},
    AaveV3Gnosis: {configs: {OTHERS: {}}, cache: {blockNumber: 47668794}},
    AaveV3Mantle: {configs: {OTHERS: {}}, cache: {blockNumber: 99156810}},
    AaveV3Plasma: {configs: {OTHERS: {}}, cache: {blockNumber: 29503521}},
    AaveV3Monad: {configs: {OTHERS: {}}, cache: {blockNumber: 95037063}},
    AaveV3XLayer: {configs: {OTHERS: {}}, cache: {blockNumber: 67674936}},
    AaveV3Ink: {configs: {OTHERS: {}}, cache: {blockNumber: 52945574}},
  },
};
