import {ConfigFile} from '../../generator/types';
export const config: ConfigFile = {
  rootOptions: {
    pools: ['AaveV3Plasma'],
    title: 'Listing of PT Ethena April Maturity on Plasma Instance',
    shortName: 'ListingOfPTEthenaAprilMaturityOnPlasmaInstance',
    date: '20251217',
    author: 'ACI',
    discussion:
      'https://governance.aave.com/t/direct-to-aip-onboard-usde-susde-april-expiry-pt-tokens-on-aave-v3-plasma-instance/23515',
    snapshot: 'direct-to-aip',
    votingNetwork: 'AVALANCHE',
  },
  poolOptions: {
    AaveV3Plasma: {
      configs: {
        EMODES_CREATION: [
          {
            ltv: '86.4',
            liqThreshold: '88.4',
            liqBonus: '4.7',
            label: 'PT_USDe_9APR2026__Stablecoins',
            collateralAssets: ['USDe', 'weETH', 'PT_USDe_15JAN2026'],
            borrowableAssets: ['USDT0', 'USDe'],
          },
          {
            ltv: '87.2',
            liqThreshold: '89.2',
            liqBonus: '3.7',
            label: 'PT_USDe_9APR2026__USDe',
            collateralAssets: ['USDe', 'weETH', 'PT_USDe_15JAN2026'],
            borrowableAssets: ['USDT0', 'USDe'],
          },
          {
            ltv: '85.5',
            liqThreshold: '87.5',
            liqBonus: '5.7',
            label: 'PT_sUSDe_9APR2026__Stablecoins',
            collateralAssets: ['sUSDe', 'XAUt0', 'PT_sUSDE_15JAN2026'],
            borrowableAssets: ['USDT0', 'USDe'],
          },
          {
            ltv: '87.2',
            liqThreshold: '89.2',
            liqBonus: '3.7',
            label: 'PT_sUSDe_9APR2026__USDe',
            collateralAssets: ['sUSDe', 'XAUt0', 'PT_sUSDE_15JAN2026'],
            borrowableAssets: ['USDe'],
          },
        ],
        ASSET_LISTING: [
          {
            assetSymbol: 'PT_sUSDE_9APR2026',
            decimals: 18,
            priceFeed: '0x13f2EA8dfa948c5247826283079615Ee4d0A1AA5',
            ltv: '87.2',
            liqThreshold: '0.1',
            liqBonus: '7.5',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'DISABLED',
            flashloanable: 'ENABLED',
            borrowableInIsolation: 'DISABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '45',
            supplyCap: '100000000',
            borrowCap: '1',
            rateStrategyParams: {
              optimalUtilizationRate: '45',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '10',
              variableRateSlope2: '300',
            },
            asset: '0xab509448ad489e2e1341e25cc500f2596464cc82',
            admin: '0xac140648435d03f784879cd789130F22Ef588Fcd',
          },
          {
            assetSymbol: 'PT_USDe_9APR2026',
            decimals: 18,
            priceFeed: '0x37f3a8b02BAbe4dd71acb5f214F22C09AFf607f3',
            ltv: '0.05',
            liqThreshold: '0.1',
            liqBonus: '7.5',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'DISABLED',
            flashloanable: 'ENABLED',
            borrowableInIsolation: 'DISABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '45',
            supplyCap: '40000000',
            borrowCap: '1',
            rateStrategyParams: {
              optimalUtilizationRate: '45',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '10',
              variableRateSlope2: '300',
            },
            asset: '0x54dc267be2839303ff1e323584a16e86cec4aa44',
            admin: '0xac140648435d03f784879cd789130F22Ef588Fcd',
          },
        ],
      },
      cache: {blockNumber: 9081692},
    },
  },
};
