import {ConfigFile} from '../../generator/types';
export const config: ConfigFile = {
  rootOptions: {
    configFile:
      'src/20250520_AaveV3Ethereum_OnboardUSDeJulyExpiryPTTokensAndEUSDeAugustExpiryPTTokensOnV3Core/config.ts',
    force: true,
    author: 'Aave-Chan Initiative',
    pools: ['AaveV3Ethereum'],
    title: 'Onboard USDe July expiry PT tokens and eUSDe August expiry PT tokens on V3 Core',
    shortName: 'OnboardUSDeJulyExpiryPTTokensAndEUSDeAugustExpiryPTTokensOnV3Core',
    date: '20250520',
    discussion:
      'https://governance.aave.com/t/arfc-onboard-usde-july-expiry-pt-tokens-on-aave-v3-core-instance/22041',
    snapshot: 'Direct-to-AIP',
    votingNetwork: 'POLYGON',
  },
  poolOptions: {
    AaveV3Ethereum: {
      configs: {
        EMODES_UPDATES: [
          {
            eModeCategory: 10,
            ltv: '88.1',
            liqThreshold: '91.1',
            liqBonus: '3.9',
            label: 'PT-USDe Stablecoins July 2025',
          },
          {
            eModeCategory: 11,
            ltv: '90.1',
            liqThreshold: '92.1',
            liqBonus: '2.8',
            label: 'PT-USDe USDe July 2025',
          },
          {
            eModeCategory: 12,
            ltv: '87.1',
            liqThreshold: '90.1',
            liqBonus: '4.1',
            label: 'PT-eUSDe Stablecoins August 2025',
          },
          {
            eModeCategory: 13,
            ltv: '89',
            liqThreshold: '91',
            liqBonus: '3.1',
            label: 'PT-eUSDe USDe August 2025',
          },
        ],
        EMODES_ASSETS: [
          {
            asset: 'PT_USDe_31JUL2025',
            eModeCategory: '10',
            collateral: 'ENABLED',
            borrowable: 'DISABLED',
          },
          {
            asset: 'PT_USDe_31JUL2025',
            eModeCategory: '11',
            collateral: 'ENABLED',
            borrowable: 'DISABLED',
          },
          {
            asset: 'PT_eUSDe_14AUG2025',
            eModeCategory: '12',
            collateral: 'ENABLED',
            borrowable: 'DISABLED',
          },
          {
            asset: 'PT_eUSDe_14AUG2025',
            eModeCategory: '13',
            collateral: 'ENABLED',
            borrowable: 'DISABLED',
          },
          {asset: 'USDC', eModeCategory: '10', collateral: 'DISABLED', borrowable: 'ENABLED'},
          {asset: 'USDT', eModeCategory: '10', collateral: 'DISABLED', borrowable: 'ENABLED'},
          {asset: 'USDe', eModeCategory: '11', collateral: 'DISABLED', borrowable: 'ENABLED'},
          {asset: 'USDS', eModeCategory: '10', collateral: 'DISABLED', borrowable: 'ENABLED'},
          {asset: 'USDC', eModeCategory: '12', collateral: 'DISABLED', borrowable: 'ENABLED'},
          {asset: 'USDT', eModeCategory: '12', collateral: 'DISABLED', borrowable: 'ENABLED'},
          {asset: 'USDe', eModeCategory: '13', collateral: 'DISABLED', borrowable: 'ENABLED'},
          {asset: 'USDS', eModeCategory: '12', collateral: 'DISABLED', borrowable: 'ENABLED'},
        ],
        ASSET_LISTING: [
          {
            assetSymbol: 'PT_USDe_31JUL2025',
            decimals: 18,
            priceFeed: '0xC26D4a1c46d884cfF6dE9800B6aE7A8Cf48B4Ff8',
            ltv: '0.05',
            liqThreshold: '0.1',
            liqBonus: '7.5',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'DISABLED',
            flashloanable: 'ENABLED',
            borrowableInIsolation: 'DISABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '45',
            supplyCap: '40000000',
            borrowCap: '1',
            rateStrategyParams: {
              optimalUtilizationRate: '45',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '10',
              variableRateSlope2: '300',
            },
            asset: '0x917459337caac939d41d7493b3999f571d20d667',
            admin: '0xac140648435d03f784879cd789130F22Ef588Fcd',
          },
          {
            assetSymbol: 'PT_eUSDe_14AUG2025',
            decimals: 18,
            priceFeed: '0x5292AB3292D076271f853Ed8e05e61cc02F0A2C6',
            ltv: '0.05',
            liqThreshold: '0.1',
            liqBonus: '7.5',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'DISABLED',
            flashloanable: 'ENABLED',
            borrowableInIsolation: 'DISABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '45',
            supplyCap: '100000000',
            borrowCap: '1',
            rateStrategyParams: {
              optimalUtilizationRate: '45',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '10',
              variableRateSlope2: '300',
            },
            asset: '0x14bdc3a3ae09f5518b923b69489cbcafb238e617',
            admin: '0xac140648435d03f784879cd789130F22Ef588Fcd',
          },
        ],
      },
      cache: {blockNumber: 22523957},
    },
  },
};
