import {ConfigFile} from '../../generator/types';
export const config: ConfigFile = {
  rootOptions: {
    pools: ['AaveV3Ethereum'],
    title: 'Ethena PT FEB Listing',
    shortName: 'EthenaPTFEBListing',
    date: '20251111',
    author: 'ACI',
    discussion:
      'https://governance.aave.com/t/direct-to-aip-onboard-usde-susde-february-expiry-pt-tokens-on-aave-v3-core-instance/23358',
    snapshot: 'Direct to AIP',
    votingNetwork: 'AVALANCHE',
  },
  poolOptions: {
    AaveV3Ethereum: {
      configs: {
        EMODES_CREATION: [
          {
            ltv: '88.5',
            liqThreshold: '90.5',
            liqBonus: '4.1',
            label: 'PTUSDe5FEBStablecoins',
            collateralAssets: ['WETH'],
            borrowableAssets: ['USDC', 'USDT', 'USDe', 'USDtb'],
          },
          {
            ltv: '89.3',
            liqThreshold: '91.3',
            liqBonus: '3.1',
            label: 'PTUSDe5FEBUSDe',
            collateralAssets: ['WETH', 'PT_USDe_27NOV2025'],
            borrowableAssets: ['USDe'],
          },
          {
            ltv: '87.6',
            liqThreshold: '89.6',
            liqBonus: '5.1',
            label: 'PTsUSDe5FEBStablecoins',
            collateralAssets: ['wstETH', 'PT_sUSDE_27NOV2025'],
            borrowableAssets: ['USDC', 'USDT', 'USDe', 'USDtb'],
          },
          {
            ltv: '88.5',
            liqThreshold: '90.5',
            liqBonus: '4.1',
            label: 'PTsUSDe5FEBUSDe',
            collateralAssets: ['wstETH', 'PT_sUSDE_27NOV2025'],
            borrowableAssets: ['USDe'],
          },
        ],
        ASSET_LISTING: [
          {
            assetSymbol: 'PT_USDE_5FEB_2026',
            decimals: 18,
            priceFeed: '0xc35D319FA5FEc2BBE0eB4d0a826465b60f821F81',
            ltv: '0.05',
            liqThreshold: '0.10',
            liqBonus: '7.5',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'DISABLED',
            flashloanable: 'ENABLED',
            borrowableInIsolation: 'DISABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '45',
            supplyCap: '30000000',
            borrowCap: '1',
            rateStrategyParams: {
              optimalUtilizationRate: '45',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '10',
              variableRateSlope2: '300',
            },
            asset: '0x1F84a51296691320478c98b8d77f2Bbd17D34350',
            admin: '0xac140648435d03f784879cd789130F22Ef588Fcd',
          },
          {
            assetSymbol: 'PT_sUSDe_5FEB_2026',
            decimals: 18,
            priceFeed: '0x4e89f87F24C13819bBDDb56f99b38746C91677D8',
            ltv: '0.05',
            liqThreshold: '0.1',
            liqBonus: '7.5',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'DISABLED',
            flashloanable: 'ENABLED',
            borrowableInIsolation: 'DISABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '45',
            supplyCap: '30000000',
            borrowCap: '1',
            rateStrategyParams: {
              optimalUtilizationRate: '45',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '10',
              variableRateSlope2: '300',
            },
            asset: '0xE8483517077afa11A9B07f849cee2552f040d7b2',
            admin: '0xac140648435d03f784879cd789130F22Ef588Fcd',
          },
        ],
      },
      cache: {blockNumber: 23790560},
    },
  },
};
