import {ConfigFile} from '../../generator/types';
export const config: ConfigFile = {
  rootOptions: {
    author: 'Aavechan Initiative @aci',
    pools: ['AaveV3InkWhitelabel'],
    title: 'sUSDe & USDe Listing Ink',
    shortName: 'SUSDeUSDeListingInk',
    date: '20260210',
  },
  poolOptions: {
    AaveV3InkWhitelabel: {
      configs: {
        EMODES_CREATION: [
          {
            ltv: '90',
            liqThreshold: '92',
            liqBonus: '4',
            label: 'sUSDe_USDe__USDT0_USDC_USDG',
            collateralAssets: ['WETH', 'kBTC'],
            borrowableAssets: ['USDT', 'USDG', 'USDC'],
          },
          {
            ltv: '90',
            liqThreshold: '93',
            liqBonus: '2',
            label: 'USDe__USDT0_USDC_USDG',
            collateralAssets: ['WETH'],
            borrowableAssets: ['USDT', 'USDG', 'USDC'],
          },
        ],
        ASSET_LISTING: [
          {
            assetSymbol: 'sUSDe',
            decimals: 18,
            priceFeed: '0xC170637d22Ac02bAC99ED794038d2676d712e704',
            ltv: '0',
            liqThreshold: '0',
            liqBonus: '0',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'DISABLED',
            flashloanable: 'ENABLED',
            borrowableInIsolation: 'DISABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '50',
            supplyCap: '50000000',
            borrowCap: '1',
            rateStrategyParams: {
              optimalUtilizationRate: '45',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '10',
              variableRateSlope2: '300',
            },
            asset: '0x211Cc4DD073734dA055fbF44a2b4667d5E5fE5d2',
            admin: '0xac140648435d03f784879cd789130F22Ef588Fcd',
          },
          {
            assetSymbol: 'USDe',
            decimals: 18,
            priceFeed: '0x24FdD142b34C6B5D55299709DB0966681933c9aF',
            ltv: '0',
            liqThreshold: '0',
            liqBonus: '0',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'ENABLED',
            flashloanable: 'ENABLED',
            borrowableInIsolation: 'DISABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '25',
            supplyCap: '50000000',
            borrowCap: '45000000',
            rateStrategyParams: {
              optimalUtilizationRate: '80',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '5.25',
              variableRateSlope2: '12',
            },
            asset: '0x5d3a1Ff2b6BAb83b63cd9AD0787074081a52ef34',
            admin: '0xac140648435d03f784879cd789130F22Ef588Fcd',
          },
        ],
      },
      cache: {blockNumber: 37261897},
    },
  },
};
