import {ConfigFile} from '../../generator/types';
export const config: ConfigFile = {
  rootOptions: {
    pools: ['AaveV3Celo'],
    title: 'Aave V3.3 Celo Activation',
    shortName: 'AaveV33CeloActivation',
    date: '20250224',
    author: 'BGD Labs (@bgdlabs)',
    discussion: 'https://governance.aave.com/t/arfc-aave-deployment-on-celo/17636',
    snapshot:
      'https://snapshot.box/#/aave.eth/proposal/0x645981c18f5dc61c07324a39d57bcb873ebd8fb9e4a435280cac57cb07a8090b',
    votingNetwork: 'POLYGON',
  },
  poolOptions: {
    AaveV3Celo: {
      configs: {
        ASSET_LISTING: [
          {
            assetSymbol: 'USDC',
            decimals: 6,
            priceFeed: '0xBF704f2FfdB856805cE64D085cD50427823696D7',
            ltv: '75',
            liqThreshold: '78',
            liqBonus: '5',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'ENABLED',
            flashloanable: 'ENABLED',
            borrowableInIsolation: 'ENABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '10',
            supplyCap: '3500000',
            borrowCap: '3150000',
            rateStrategyParams: {
              optimalUtilizationRate: '90',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '7.5',
              variableRateSlope2: '40',
            },
            asset: '0xcebA9300f2b948710d2653dD7B07f33A8B32118C',
            admin: '',
          },
          {
            assetSymbol: 'USDT',
            decimals: 6,
            priceFeed: '0x6e3d991C965364481796116dE68A8036d1b3Ecd0',
            ltv: '75',
            liqThreshold: '78',
            liqBonus: '5',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'ENABLED',
            flashloanable: 'ENABLED',
            borrowableInIsolation: 'ENABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '10',
            supplyCap: '2000000',
            borrowCap: '1800000',
            rateStrategyParams: {
              optimalUtilizationRate: '90',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '7.5',
              variableRateSlope2: '40',
            },
            asset: '0x48065fbBE25f71C9282ddf5e1cD6D6A887483D5e',
            admin: '',
          },
          {
            assetSymbol: 'cEUR',
            decimals: 18,
            priceFeed: '0x3D207061Dbe8E2473527611BFecB87Ff12b28dDa',
            ltv: '0',
            liqThreshold: '0',
            liqBonus: '0',
            debtCeiling: '0',
            liqProtocolFee: '0',
            enabledToBorrow: 'ENABLED',
            flashloanable: 'ENABLED',
            borrowableInIsolation: 'ENABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '15',
            supplyCap: '80000',
            borrowCap: '72000',
            rateStrategyParams: {
              optimalUtilizationRate: '90',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '7.5',
              variableRateSlope2: '75',
            },
            asset: '0xd8763cba276a3738e6de85b4b3bf5fded6d6ca73',
            admin: '',
          },
          {
            assetSymbol: 'cUSD',
            decimals: 18,
            priceFeed: '0xdCdA3E7E90fe827776b8FDaEa3C5977F123354DA',
            ltv: '0',
            liqThreshold: '0',
            liqBonus: '0',
            debtCeiling: '0',
            liqProtocolFee: '0',
            enabledToBorrow: 'ENABLED',
            flashloanable: 'ENABLED',
            borrowableInIsolation: 'ENABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '15',
            supplyCap: '1300000',
            borrowCap: '1170000',
            rateStrategyParams: {
              optimalUtilizationRate: '90',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '7.5',
              variableRateSlope2: '75',
            },
            asset: '0x765de816845861e75a25fca122bb6898b8b1282a',
            admin: '',
          },
          {
            assetSymbol: 'CELO',
            decimals: 18,
            priceFeed: '0x0568fD19986748cEfF3301e55c0eb1E729E0Ab7e',
            ltv: '55',
            liqThreshold: '61',
            liqBonus: '10',
            debtCeiling: '500000',
            liqProtocolFee: '10',
            enabledToBorrow: 'ENABLED',
            flashloanable: 'ENABLED',
            borrowableInIsolation: 'DISABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '20',
            supplyCap: '1000000',
            borrowCap: '100000',
            rateStrategyParams: {
              optimalUtilizationRate: '45',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '10',
              variableRateSlope2: '150',
            },
            asset: '0x471ece3750da237f93b8e339c536989b8978a438',
            admin: '',
          },
        ],
      },
      cache: {blockNumber: 30541450},
    },
  },
};
