import {ConfigFile} from '../../generator/types';
export const config: ConfigFile = {
  rootOptions: {
    markets: [
      'AaveV3Ethereum',
      'AaveV3EthereumLido',
      'AaveV3EthereumEtherFi',
      'AaveV3Polygon',
      'AaveV3Avalanche',
      'AaveV3Arbitrum',
      'AaveV3Optimism',
      'AaveV3Base',
      'AaveV3Gnosis',
      'AaveV3BNB',
      'AaveV3Scroll',
      'AaveV3Linea',
      'AaveV3Sonic',
      'AaveV3Celo',
      'AaveV3Mantle',
      'AaveV3Plasma',
      'AaveV3MegaEth',
      'AaveV3Monad',
      'AaveV3XLayer',
    ],
    title: 'Risk Stewards Cooldown Reduction & Umbrella Pauser Role Reassignment',
    shortName: 'RiskStewardsCooldownReductionAndUmbrellaPauserRoleReassignment',
    date: '20260720',
    author: 'Llama Risk (implemented by Aave Labs)',
    discussion:
      'https://governance.aave.com/t/arfc-risk-stewards-cooldown-reduction-umbrella-pauser-role-reassignment/25068',
    snapshot:
      'https://snapshot.org/#/aavedao.eth/proposal/0x7083921f2f549ffa2cdc294c8ff60fdc82af0becbb7b2f20f4f296c34694aaf2',
    votingNetwork: 'AVALANCHE',
  },
  marketOptions: {
    AaveV3Ethereum: {configs: {OTHERS: {}}, cache: {blockNumber: 25774279}},
    AaveV3EthereumLido: {configs: {OTHERS: {}}, cache: {blockNumber: 25774279}},
    AaveV3EthereumEtherFi: {configs: {OTHERS: {}}, cache: {blockNumber: 25774279}},
    AaveV3Polygon: {configs: {OTHERS: {}}, cache: {blockNumber: 92172257}},
    AaveV3Avalanche: {configs: {OTHERS: {}}, cache: {blockNumber: 93019784}},
    AaveV3Arbitrum: {configs: {OTHERS: {}}, cache: {blockNumber: 495456603}},
    AaveV3Optimism: {configs: {OTHERS: {}}, cache: {blockNumber: 155682318}},
    AaveV3Base: {configs: {OTHERS: {}}, cache: {blockNumber: 50087033}},
    AaveV3Gnosis: {configs: {OTHERS: {}}, cache: {blockNumber: 47770354}},
    AaveV3BNB: {configs: {OTHERS: {}}, cache: {blockNumber: 116450388}},
    AaveV3Scroll: {configs: {OTHERS: {}}, cache: {blockNumber: 34666447}},
    AaveV3Linea: {configs: {OTHERS: {}}, cache: {blockNumber: 31741907}},
    AaveV3Sonic: {configs: {OTHERS: {}}, cache: {blockNumber: 77652847}},
    AaveV3Celo: {configs: {OTHERS: {}}, cache: {blockNumber: 75062659}},
    AaveV3Mantle: {configs: {OTHERS: {}}, cache: {blockNumber: 99416553}},
    AaveV3Plasma: {configs: {OTHERS: {}}, cache: {blockNumber: 30022873}},
    AaveV3MegaEth: {configs: {OTHERS: {}}, cache: {blockNumber: 24166410}},
    AaveV3Monad: {configs: {OTHERS: {}}, cache: {blockNumber: 96755251}},
    AaveV3XLayer: {configs: {OTHERS: {}}, cache: {blockNumber: 68194385}},
  },
};
