import {ConfigFile} from '../../generator/types';
export const config: ConfigFile = {
  rootOptions: {
    markets: [
      'AaveV3Ethereum',
      'AaveV3EthereumLido',
      'AaveV3EthereumEtherFi',
      'AaveV3Polygon',
      'AaveV3Avalanche',
      'AaveV3Arbitrum',
      'AaveV3Optimism',
      'AaveV3Base',
      'AaveV3Gnosis',
      'AaveV3BNB',
      'AaveV3Scroll',
      'AaveV3Linea',
      'AaveV3Sonic',
      'AaveV3Celo',
      'AaveV3Mantle',
      'AaveV3Plasma',
      'AaveV3MegaEth',
      'AaveV3Monad',
      'AaveV3XLayer',
    ],
    title: 'Risk Stewards Cooldown Reduction & Umbrella Pauser Role Reassignment',
    shortName: 'RiskStewardsCooldownReductionAndUmbrellaPauserRoleReassignment',
    date: '20260720',
    author: 'Llama Risk (implemented by Aave Labs)',
    discussion:
      'https://governance.aave.com/t/arfc-risk-stewards-cooldown-reduction-umbrella-pauser-role-reassignment/25068',
    snapshot:
      'https://snapshot.org/#/aavedao.eth/proposal/0x7083921f2f549ffa2cdc294c8ff60fdc82af0becbb7b2f20f4f296c34694aaf2',
    votingNetwork: 'AVALANCHE',
  },
  marketOptions: {
    AaveV3Ethereum: {configs: {OTHERS: {}}, cache: {blockNumber: 25573446}},
    AaveV3EthereumLido: {configs: {OTHERS: {}}, cache: {blockNumber: 25573446}},
    AaveV3EthereumEtherFi: {configs: {OTHERS: {}}, cache: {blockNumber: 25573446}},
    AaveV3Polygon: {configs: {OTHERS: {}}, cache: {blockNumber: 90559817}},
    AaveV3Avalanche: {configs: {OTHERS: {}}, cache: {blockNumber: 90784254}},
    AaveV3Arbitrum: {configs: {OTHERS: {}}, cache: {blockNumber: 485814584}},
    AaveV3Optimism: {configs: {OTHERS: {}}, cache: {blockNumber: 154472973}},
    AaveV3Base: {configs: {OTHERS: {}}, cache: {blockNumber: 48877688}},
    AaveV3Gnosis: {configs: {OTHERS: {}}, cache: {blockNumber: 47298396}},
    AaveV3BNB: {configs: {OTHERS: {}}, cache: {blockNumber: 111078294}},
    AaveV3Scroll: {configs: {OTHERS: {}}, cache: {blockNumber: 34420750}},
    AaveV3Linea: {configs: {OTHERS: {}}, cache: {blockNumber: 31451966}},
    AaveV3Sonic: {configs: {OTHERS: {}}, cache: {blockNumber: 76230463}},
    AaveV3Celo: {configs: {OTHERS: {}}, cache: {blockNumber: 72643966}},
    AaveV3Mantle: {configs: {OTHERS: {}}, cache: {blockNumber: 98207206}},
    AaveV3Plasma: {configs: {OTHERS: {}}, cache: {blockNumber: 27604372}},
    AaveV3MegaEth: {configs: {OTHERS: {}}, cache: {blockNumber: 21747715}},
    AaveV3Monad: {configs: {OTHERS: {}}, cache: {blockNumber: 88977008}},
    AaveV3XLayer: {configs: {OTHERS: {}}, cache: {blockNumber: 65775688}},
  },
};
