import {ConfigFile} from '../../generator/types';
export const config: ConfigFile = {
  rootOptions: {
    pools: ['AaveV3PolygonZkEvm'],
    title: 'Aave v3 Polygon ZkEvm activation',
    shortName: 'AaveV3PolygonZkEvmActivation',
    date: '20240112',
    author: 'BGD Labs @bgdlabs',
    discussion: 'https://governance.aave.com/t/arfc-aave-v3-deployment-on-zkevm-l2/12615',
    snapshot:
      'https://snapshot.org/#/aave.eth/proposal/0x8fd34012029bec536f779b7bf46813beb57f42705b24acaf239e42353ddf7b8c',
  },
  poolOptions: {
    AaveV3PolygonZkEvm: {
      configs: {
        ASSET_LISTING: [
          {
            assetSymbol: 'USDC',
            decimals: 6,
            priceFeed: '0x0167D934CB7240e65c35e347F00Ca5b12567523a',
            ltv: '77',
            liqThreshold: '80',
            liqBonus: '5',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'ENABLED',
            flashloanable: 'ENABLED',
            stableRateModeEnabled: 'DISABLED',
            borrowableInIsolation: 'ENABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '10',
            supplyCap: '525000',
            borrowCap: '500000',
            rateStrategyParams: {
              optimalUtilizationRate: '90',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '6',
              variableRateSlope2: '80',
              stableRateSlope1: '6',
              stableRateSlope2: '80',
              baseStableRateOffset: '1',
              stableRateExcessOffset: '8',
              optimalStableToTotalDebtRatio: '20',
            },
            eModeCategory: '0',
            asset: '0x37eaa0ef3549a5bb7d431be78a3d99bd360d19e5',
          },
          {
            assetSymbol: 'WETH',
            decimals: 18,
            priceFeed: '0x97d9F9A00dEE0004BE8ca0A8fa374d486567eE2D',
            ltv: '75',
            liqThreshold: '78',
            liqBonus: '5',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'ENABLED',
            flashloanable: 'ENABLED',
            stableRateModeEnabled: 'DISABLED',
            borrowableInIsolation: 'DISABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '15',
            supplyCap: '350',
            borrowCap: '280',
            rateStrategyParams: {
              optimalUtilizationRate: '80',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '3.3',
              variableRateSlope2: '80',
              stableRateSlope1: '3.3',
              stableRateSlope2: '80',
              baseStableRateOffset: '2',
              stableRateExcessOffset: '8',
              optimalStableToTotalDebtRatio: '20',
            },
            eModeCategory: '0',
            asset: '0x4F9A0e7FD2Bf6067db6994CF12E4495Df938E6e9',
          },
          {
            assetSymbol: 'MATIC',
            decimals: 18,
            priceFeed: '0x7C85dD6eBc1d318E909F22d51e756Cf066643341',
            ltv: '68',
            liqThreshold: '73',
            liqBonus: '7.5',
            debtCeiling: '0',
            liqProtocolFee: '10',
            enabledToBorrow: 'ENABLED',
            flashloanable: 'ENABLED',
            stableRateModeEnabled: 'DISABLED',
            borrowableInIsolation: 'DISABLED',
            withSiloedBorrowing: 'DISABLED',
            reserveFactor: '20',
            supplyCap: '700000',
            borrowCap: '525000',
            rateStrategyParams: {
              optimalUtilizationRate: '75',
              baseVariableBorrowRate: '0',
              variableRateSlope1: '5',
              variableRateSlope2: '100',
              stableRateSlope1: '5',
              stableRateSlope2: '100',
              baseStableRateOffset: '2',
              stableRateExcessOffset: '8',
              optimalStableToTotalDebtRatio: '20',
            },
            eModeCategory: '0',
            asset: '0xa2036f0538221a77A3937F1379699f44945018d0',
          },
        ],
      },
      cache: {blockNumber: 9196867},
    },
  },
};
