import {ConfigFile} from '../../generator/types';
export const config: ConfigFile = {
  rootOptions: {
    author: 'ChaosLabs (implemented by Aavechan Initiative @aci via Skyward)',
    pools: [
      'AaveV3Ethereum',
      'AaveV3EthereumLido',
      'AaveV3Polygon',
      'AaveV3Avalanche',
      'AaveV3Arbitrum',
      'AaveV3Base',
      'AaveV3BNB',
      'AaveV3Linea',
      'AaveV3Plasma',
    ],
    title: 'Enhancing Market Granularity in Aave 3.6: part 2',
    shortName: 'EnhancingMarketGranularityInAave36Part2',
    date: '20260127',
    discussion:
      'https://governance.aave.com/t/direct-to-aip-enhancing-market-granularity-in-aave-v3-6-restricting-borrowability-and-collateralization-outside-of-liquid-emodes/23592',
    snapshot: 'direct-to-AIP',
    votingNetwork: 'AVALANCHE',
  },
  poolOptions: {
    AaveV3Ethereum: {
      configs: {
        CAPS_UPDATE: [
          {asset: 'rETH', supplyCap: '', borrowCap: '1'},
          {asset: 'CRV', supplyCap: '', borrowCap: '1'},
          {asset: 'MKR', supplyCap: '', borrowCap: '1'},
          {asset: 'SNX', supplyCap: '', borrowCap: '1'},
          {asset: 'BAL', supplyCap: '', borrowCap: '1'},
          {asset: 'UNI', supplyCap: '', borrowCap: '1'},
          {asset: 'LDO', supplyCap: '', borrowCap: '1'},
          {asset: 'ENS', supplyCap: '', borrowCap: '1'},
          {asset: 'ONE_INCH', supplyCap: '', borrowCap: '1'},
          {asset: 'RPL', supplyCap: '', borrowCap: '1'},
          {asset: 'weETH', supplyCap: '', borrowCap: '1'},
          {asset: 'osETH', supplyCap: '', borrowCap: '1'},
          {asset: 'ETHx', supplyCap: '', borrowCap: '1'},
        ],
        COLLATERALS_UPDATE: [
          {
            asset: 'LINK',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'MKR',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'sDAI',
            ltv: '0',
            liqThreshold: '0.1',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'osETH',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'USDe',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'ETHx',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'sUSDe',
            ltv: '0',
            liqThreshold: '0.1',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'rsETH',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'PT_eUSDE_29MAY2025',
            ltv: '0',
            liqThreshold: '0.1',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'PT_sUSDE_31JUL2025',
            ltv: '0',
            liqThreshold: '0.1',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'PT_USDe_31JUL2025',
            ltv: '0',
            liqThreshold: '0.1',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'PT_eUSDE_14AUG2025',
            ltv: '0',
            liqThreshold: '0.1',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'eUSDe',
            ltv: '0',
            liqThreshold: '0.1',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'EURC',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'PT_sUSDE_25SEP2025',
            ltv: '00',
            liqThreshold: '0.1',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'PT_USDe_25SEP2025',
            ltv: '0',
            liqThreshold: '0.1',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'tETH',
            ltv: '0',
            liqThreshold: '0.1',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'ezETH',
            ltv: '0',
            liqThreshold: '0.1',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'XAUt',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'PT_sUSDE_27NOV2025',
            ltv: '0',
            liqThreshold: '0.1',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'PT_USDe_27NOV2025',
            ltv: '0',
            liqThreshold: '0.1',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
        ],
        BORROWS_UPDATE: [
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'wstETH',
          },
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'cbETH',
          },
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'rETH',
          },
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'CRV',
          },
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'MKR',
          },
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'SNX',
          },
          {
            enabledToBorrow: 'KEEP_CURRENT',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'BAL',
          },
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'UNI',
          },
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'LDO',
          },
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'ENS',
          },
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'ONE_INCH',
          },
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'RPL',
          },
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'weETH',
          },
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'osETH',
          },
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'ETHx',
          },
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'FBTC',
          },
        ],
        EMODES_CREATION: [
          {
            ltv: '66',
            liqThreshold: '71',
            liqBonus: '7',
            label: 'LINK__USDC_USDT',
            collateralAssets: ['LINK'],
            borrowableAssets: ['USDC', 'USDT'],
          },
          {
            ltv: '75',
            liqThreshold: '78',
            liqBonus: '5',
            label: 'EURC__USDC_USDT_GHO',
            collateralAssets: ['EURC'],
            borrowableAssets: ['USDC', 'USDT', 'GHO'],
          },
          {
            ltv: '75',
            liqThreshold: '78',
            liqBonus: '7.5',
            label: 'rsETH__USDC_USDT',
            collateralAssets: ['rsETH'],
            borrowableAssets: ['USDC', 'USDT'],
          },
          {
            ltv: '70',
            liqThreshold: '75',
            liqBonus: '6',
            label: 'XAUt__USDC_USDT_GHO',
            collateralAssets: ['XAUt'],
            borrowableAssets: ['USDC', 'USDT', 'GHO'],
          },
        ],
      },
      cache: {blockNumber: 24322270},
    },
    AaveV3EthereumLido: {
      configs: {
        COLLATERALS_UPDATE: [
          {
            asset: 'ezETH',
            ltv: '0',
            liqThreshold: '0.1',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'sUSDe',
            ltv: '0',
            liqThreshold: '0.1',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'rsETH',
            ltv: '0',
            liqThreshold: '0.1',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'tETH',
            ltv: '0',
            liqThreshold: '0.1',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
        ],
        BORROWS_UPDATE: [
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'wstETH',
          },
        ],
      },
      cache: {blockNumber: 24322444},
    },
    AaveV3Polygon: {
      configs: {
        CAPS_UPDATE: [
          {asset: 'LINK', supplyCap: '', borrowCap: '1'},
          {asset: 'EURS', supplyCap: '', borrowCap: '1'},
          {asset: 'MaticX', supplyCap: '', borrowCap: '1'},
        ],
        COLLATERALS_UPDATE: [
          {
            asset: 'LINK',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'AAVE',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'MaticX',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
        ],
        BORROWS_UPDATE: [
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'LINK',
          },
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'USDC',
          },
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'WPOL',
          },
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'EURS',
          },
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'MaticX',
          },
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'wstETH',
          },
        ],
        EMODES_CREATION: [
          {
            ltv: '63',
            liqThreshold: '70',
            liqBonus: '7.5',
            label: 'AAVE__USDCn_USDT',
            collateralAssets: ['AAVE'],
            borrowableAssets: ['USDT0', 'USDCn'],
          },
        ],
      },
      cache: {blockNumber: 82176087},
    },
    AaveV3Avalanche: {
      configs: {
        CAPS_UPDATE: [{asset: 'LINKe', supplyCap: '', borrowCap: '1'}],
        COLLATERALS_UPDATE: [
          {
            asset: 'LINKe',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'AAVEe',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'FRAX',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'EURC',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
        ],
        BORROWS_UPDATE: [
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'LINKe',
          },
        ],
        EMODES_CREATION: [
          {
            ltv: '75',
            liqThreshold: '78',
            liqBonus: '5',
            label: 'EURC__USDC_USDT',
            collateralAssets: ['EURC'],
            borrowableAssets: ['USDC', 'USDt'],
          },
        ],
      },
      cache: {blockNumber: 76613800},
    },
    AaveV3Arbitrum: {
      configs: {
        CAPS_UPDATE: [
          {asset: 'LINK', supplyCap: '', borrowCap: '1'},
          {asset: 'rETH', supplyCap: '', borrowCap: '1'},
          {asset: 'LUSD', supplyCap: '', borrowCap: '1'},
          {asset: 'ARB', supplyCap: '', borrowCap: '1'},
          {asset: 'weETH', supplyCap: '', borrowCap: '1'},
        ],
        COLLATERALS_UPDATE: [
          {
            asset: 'LINK',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'USDC',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'AAVE',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'ARB',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'ezETH',
            ltv: '0',
            liqThreshold: '0.1',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'rsETH',
            ltv: '0',
            liqThreshold: '0.1',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'tBTC',
            ltv: '0',
            liqThreshold: '0.1',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
        ],
        BORROWS_UPDATE: [
          {
            enabledToBorrow: 'KEEP_CURRENT',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'LINK',
          },
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'USDC',
          },
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'wstETH',
          },
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'rETH',
          },
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'LUSD',
          },
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'FRAX',
          },
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'ARB',
          },
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'weETH',
          },
        ],
        EMODES_CREATION: [
          {
            ltv: '66',
            liqThreshold: '73',
            liqBonus: '10',
            label: 'AAVE__USDC_USDT',
            collateralAssets: ['AAVE'],
            borrowableAssets: ['USDT', 'USDCn'],
          },
          {
            ltv: '58',
            liqThreshold: '63',
            liqBonus: '10',
            label: 'ARB__USDC_USDT',
            collateralAssets: ['ARB'],
            borrowableAssets: ['USDT', 'USDCn'],
          },
          {
            ltv: '72',
            liqThreshold: '75',
            liqBonus: '7.5',
            label: 'tBTC__USDC_USDT',
            collateralAssets: ['tBTC'],
            borrowableAssets: ['USDT', 'USDCn'],
          },
        ],
      },
      cache: {blockNumber: 425586342},
    },
    AaveV3Base: {
      configs: {
        CAPS_UPDATE: [{asset: 'weETH', supplyCap: '', borrowCap: '1'}],
        COLLATERALS_UPDATE: [
          {
            asset: 'USDbC',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'ezETH',
            ltv: '0',
            liqThreshold: '0.1',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'wrsETH',
            ltv: '0',
            liqThreshold: '0.1',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'LBTC',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'EURC',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'AAVE',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'tBTC',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
        ],
        BORROWS_UPDATE: [
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'cbETH',
          },
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'USDbC',
          },
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'wstETH',
          },
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'weETH',
          },
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'tBTC',
          },
        ],
        EMODES_CREATION: [
          {
            ltv: '63',
            liqThreshold: '70',
            liqBonus: '10',
            label: 'AAVE__USDC_GHO',
            collateralAssets: ['AAVE'],
            borrowableAssets: ['USDC', 'GHO'],
          },
          {
            ltv: '75',
            liqThreshold: '78',
            liqBonus: '5',
            label: 'EURC__USDC_GHO',
            collateralAssets: ['EURC'],
            borrowableAssets: ['USDC', 'GHO'],
          },
          {
            ltv: '75',
            liqThreshold: '78',
            liqBonus: '5',
            label: 'LBTC__USDC_GHO',
            collateralAssets: ['LBTC'],
            borrowableAssets: ['USDC', 'GHO'],
          },
          {
            ltv: '72',
            liqThreshold: '75',
            liqBonus: '7.5',
            label: 'tBTC__USDC_GHO',
            collateralAssets: ['tBTC'],
            borrowableAssets: ['USDC', 'GHO'],
          },
        ],
      },
      cache: {blockNumber: 41342635},
    },
    AaveV3BNB: {
      configs: {
        COLLATERALS_UPDATE: [
          {
            asset: 'FDUSD',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
        ],
        EMODES_CREATION: [
          {
            ltv: '0',
            liqThreshold: '0',
            liqBonus: '0',
            label: 't',
            collateralAssets: ['Cake'],
            borrowableAssets: ['Cake'],
          },
        ],
      },
      cache: {blockNumber: 77621945},
    },
    AaveV3Linea: {
      configs: {
        CAPS_UPDATE: [{asset: 'weETH', supplyCap: '', borrowCap: '1'}],
        COLLATERALS_UPDATE: [
          {
            asset: 'ezETH',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'wrsETH',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
        ],
        BORROWS_UPDATE: [
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'wstETH',
          },
          {
            enabledToBorrow: 'DISABLED',
            flashloanable: 'KEEP_CURRENT',
            borrowableInIsolation: 'KEEP_CURRENT',
            withSiloedBorrowing: 'KEEP_CURRENT',
            reserveFactor: '',
            asset: 'weETH',
          },
        ],
        EMODES_CREATION: [
          {
            ltv: '72.5',
            liqThreshold: '75',
            liqBonus: '7.5',
            label: 'ezETH__USDC_USDT',
            collateralAssets: ['ezETH'],
            borrowableAssets: ['USDC', 'USDT'],
          },
        ],
      },
      cache: {blockNumber: 28352877},
    },
    AaveV3Plasma: {
      configs: {
        COLLATERALS_UPDATE: [
          {
            asset: 'USDe',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
          {
            asset: 'XAUt0',
            ltv: '0',
            liqThreshold: '',
            liqBonus: '',
            debtCeiling: '0',
            liqProtocolFee: '',
          },
          {
            asset: 'weETH',
            ltv: '0',
            liqThreshold: '0.1',
            liqBonus: '',
            debtCeiling: '',
            liqProtocolFee: '',
          },
        ],
        EMODES_CREATION: [
          {
            ltv: '70',
            liqThreshold: '75',
            liqBonus: '7.5',
            label: 'XAUt__USDC_USDT_GHO',
            collateralAssets: ['XAUt0'],
            borrowableAssets: ['USDT0'],
          },
        ],
      },
      cache: {blockNumber: 12543763},
    },
  },
};
