name: PR Comment

on:
  workflow_run:
    workflows: [Test]
    types:
      - completed

jobs:
  test:
    uses: bgd-labs/github-workflows/.github/workflows/comment.yml@main
    secrets:
      READ_ONLY_PAT: ${{ secrets.READ_ONLY_PAT }}
