import {ConfigFile} from '../../generator/types';
export const config: ConfigFile = {
  rootOptions: {
    configFile: 'src/20260723_Multi_AaveV4Round11CapUpdates/config.ts',
    force: true,
    markets: ['AaveV4Ethereum', 'AaveV4Avalanche'],
    title: 'Aave V4 Round 11 Cap Updates',
    shortName: 'AaveV4Round11CapUpdates',
    date: '20260723',
    author: 'LlamaRisk (implemented by Aave Labs)',
    discussion:
      'https://governance.aave.com/t/arfc-aave-v4-activation-on-ethereum-mainnet/24293/38',
    snapshot: 'direct-to-aip',
    votingNetwork: 'AVALANCHE',
  },
  marketOptions: {
    AaveV4Ethereum: {
      configs: {
        V4_HUB_SPOKE_CONFIG_UPDATE: [
          {
            hubLib: 'AaveV4EthereumHubs.CORE_HUB',
            hub: 'CORE_HUB',
            underlying: 'AaveV4EthereumAssets.WETH_UNDERLYING',
            spoke: 'AaveV4EthereumSpokes.ETHERFI_ESPOKE',
            addCap: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            drawCap: {kind: 'literal', value: '20_000'},
            riskPremiumThreshold: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            active: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            halted: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
          },
          {
            hubLib: 'AaveV4EthereumHubs.CORE_HUB',
            hub: 'CORE_HUB',
            underlying: 'AaveV4EthereumAssets.weETH_UNDERLYING',
            spoke: 'AaveV4EthereumSpokes.ETHERFI_ESPOKE',
            addCap: {kind: 'literal', value: '28_000'},
            drawCap: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            riskPremiumThreshold: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            active: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            halted: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
          },
          {
            hubLib: 'AaveV4EthereumHubs.CORE_HUB',
            hub: 'CORE_HUB',
            underlying: 'AaveV4EthereumAssets.USDG_UNDERLYING',
            spoke: 'AaveV4EthereumSpokes.GOLD_SPOKE',
            addCap: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            drawCap: {kind: 'literal', value: '2_000_000'},
            riskPremiumThreshold: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            active: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            halted: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
          },
          {
            hubLib: 'AaveV4EthereumHubs.CORE_HUB',
            hub: 'CORE_HUB',
            underlying: 'AaveV4EthereumAssets.XAUt_UNDERLYING',
            spoke: 'AaveV4EthereumSpokes.GOLD_SPOKE',
            addCap: {kind: 'literal', value: '3_800'},
            drawCap: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            riskPremiumThreshold: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            active: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            halted: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
          },
          {
            hubLib: 'AaveV4EthereumHubs.CORE_HUB',
            hub: 'CORE_HUB',
            underlying: 'AaveV4EthereumAssets.frxUSD_UNDERLYING',
            spoke: 'AaveV4EthereumSpokes.GOLD_SPOKE',
            addCap: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            drawCap: {kind: 'literal', value: '2_000_000'},
            riskPremiumThreshold: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            active: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            halted: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
          },
          {
            hubLib: 'AaveV4EthereumHubs.CORE_HUB',
            hub: 'CORE_HUB',
            underlying: 'AaveV4EthereumAssets.LINK_UNDERLYING',
            spoke: 'AaveV4EthereumSpokes.MAIN_SPOKE',
            addCap: {kind: 'literal', value: '900_000'},
            drawCap: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            riskPremiumThreshold: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            active: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            halted: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
          },
          {
            hubLib: 'AaveV4EthereumHubs.CORE_HUB',
            hub: 'CORE_HUB',
            underlying: 'AaveV4EthereumAssets.USDG_UNDERLYING',
            spoke: 'AaveV4EthereumSpokes.MAIN_SPOKE',
            addCap: {kind: 'literal', value: '65_000_000'},
            drawCap: {kind: 'literal', value: '35_000_000'},
            riskPremiumThreshold: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            active: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            halted: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
          },
          {
            hubLib: 'AaveV4EthereumHubs.CORE_HUB',
            hub: 'CORE_HUB',
            underlying: 'AaveV4EthereumAssets.WBTC_UNDERLYING',
            spoke: 'AaveV4EthereumSpokes.MAIN_SPOKE',
            addCap: {kind: 'literal', value: '1_350'},
            drawCap: {kind: 'literal', value: '120'},
            riskPremiumThreshold: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            active: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            halted: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
          },
          {
            hubLib: 'AaveV4EthereumHubs.CORE_HUB',
            hub: 'CORE_HUB',
            underlying: 'AaveV4EthereumAssets.WETH_UNDERLYING',
            spoke: 'AaveV4EthereumSpokes.MAIN_SPOKE',
            addCap: {kind: 'literal', value: '38_000'},
            drawCap: {kind: 'literal', value: '3_300'},
            riskPremiumThreshold: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            active: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            halted: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
          },
          {
            hubLib: 'AaveV4EthereumHubs.PRIME_HUB',
            hub: 'PRIME_HUB',
            underlying: 'AaveV4EthereumAssets.WBTC_UNDERLYING',
            spoke: 'AaveV4EthereumSpokes.BLUECHIP_SPOKE',
            addCap: {kind: 'literal', value: '700'},
            drawCap: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            riskPremiumThreshold: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            active: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            halted: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
          },
          {
            hubLib: 'AaveV4EthereumHubs.PRIME_HUB',
            hub: 'PRIME_HUB',
            underlying: 'AaveV4EthereumAssets.WETH_UNDERLYING',
            spoke: 'AaveV4EthereumSpokes.BLUECHIP_SPOKE',
            addCap: {kind: 'literal', value: '8_000'},
            drawCap: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            riskPremiumThreshold: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            active: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            halted: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
          },
          {
            hubLib: 'AaveV4EthereumHubs.PRIME_HUB',
            hub: 'PRIME_HUB',
            underlying: 'AaveV4EthereumAssets.cbBTC_UNDERLYING',
            spoke: 'AaveV4EthereumSpokes.BLUECHIP_SPOKE',
            addCap: {kind: 'literal', value: '300'},
            drawCap: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            riskPremiumThreshold: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            active: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            halted: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
          },
          {
            hubLib: 'AaveV4EthereumHubs.PRIME_HUB',
            hub: 'PRIME_HUB',
            underlying: 'AaveV4EthereumAssets.wstETH_UNDERLYING',
            spoke: 'AaveV4EthereumSpokes.BLUECHIP_SPOKE',
            addCap: {kind: 'literal', value: '14_000'},
            drawCap: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            riskPremiumThreshold: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            active: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            halted: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
          },
        ],
      },
      cache: {blockNumber: 25595214},
    },
    AaveV4Avalanche: {
      configs: {
        V4_HUB_SPOKE_CONFIG_UPDATE: [
          {
            hubLib: 'AaveV4AvalancheHubs.CORE_HUB',
            hub: 'CORE_HUB',
            underlying: 'AaveV4AvalancheAssets.USDC_UNDERLYING',
            spoke: 'AaveV4AvalancheSpokes.FOREX_SPOKE',
            addCap: {kind: 'literal', value: '400_000'},
            drawCap: {kind: 'literal', value: '350_000'},
            riskPremiumThreshold: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            active: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            halted: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
          },
          {
            hubLib: 'AaveV4AvalancheHubs.CORE_HUB',
            hub: 'CORE_HUB',
            underlying: 'AaveV4AvalancheAssets.USDt_UNDERLYING',
            spoke: 'AaveV4AvalancheSpokes.FOREX_SPOKE',
            addCap: {kind: 'literal', value: '400_000'},
            drawCap: {kind: 'literal', value: '350_000'},
            riskPremiumThreshold: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            active: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
            halted: {kind: 'keepCurrent', sentinel: 'KEEP_CURRENT'},
          },
        ],
      },
      cache: {blockNumber: 91036002},
    },
  },
};
